# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, null=True, verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Категории',
                'verbose_name': 'Категория',
                'ordering': ['name'],
            },
        ),
    ]
